Fix type for timeout option
There is a runtime check which will throw an error if timeout is set to true, along the lines of:

error: Job #1 named "exampleJob" had an invalid timeout of true

Now its type safe at runtime and build/dev time